[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
core = { path = "../core" }
chrono = "0.4.42"
crossterm = "0.28"
regex = "1.12.2"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
rexpect = "0.6.2"
indoc = "2.0"
tempfile = "3.24.0"